#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);

$exitCode = $application->run();

exit($exitCode);
